name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  schedule:
    - cron: '0 0 * * 0'

  push:
    branches:
      - main
   
    
  

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]
      fail-fast: false

    steps:
      # Check out the code from the repository.
      - name: Get code from repo
        uses: actions/checkout@v3 
      # Set up a Node.js environment using the specified node version.
      - name: Do Node.js environment setup for ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - name: Install node dependencies
        run: cd backend && npm install

      # Run the tests.
      - name: Run node tests
        run: cd backend && npm test

      # Setup the linter
      - name: Linter needs a config to work
        run: cd backend && npm init @eslint/config

      # Run the linter.
      - name: Run code linter
        run: cd backend && npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
